
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftHelloTypes ///

public protocol SwiftHelloTypes: JavaProtocol {

}


open class SwiftHelloTypesForward: JNIObjectForward, SwiftHelloTypes {

    private static var SwiftHelloTypesJNIClass: jclass?

}

