
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftHelloTest ///

public protocol SwiftHelloTest: JavaProtocol {

}


open class SwiftHelloTestForward: JNIObjectForward, SwiftHelloTest {

    private static var SwiftHelloTestJNIClass: jclass?

}

