
/// generated by: genswift.java 'java/lang|java/util|java/sql' 'Sources' '../java' ///

/// interface com.johnholdsworth.swiftbindings.SwiftHelloBinding$RenderListener ///

package org.swiftjava.com_johnholdsworth;

@SuppressWarnings("JniMissingFunction")
public class SwiftHelloBinding_RenderListenerProxy implements com.johnholdsworth.swiftbindings.SwiftHelloBinding.RenderListener {

    // address of proxy object
    long __swiftObject;

    SwiftHelloBinding_RenderListenerProxy( long __swiftObject ) {
        this.__swiftObject = __swiftObject;
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftHelloBinding$RenderListener.drawPoint(int,int)

    public native void __drawPoint( long __swiftObject, int x, int y );

    public void drawPoint( int x, int y ) {
        __drawPoint( __swiftObject, x, y );
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftHelloBinding$RenderListener.onDrawFrame()

    public native void __onDrawFrame( long __swiftObject );

    public void onDrawFrame() {
        __onDrawFrame( __swiftObject  );
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftHelloBinding$RenderListener.onSurfaceChanged(int,int)

    public native void __onSurfaceChanged( long __swiftObject, int width, int height );

    public void onSurfaceChanged( int width, int height ) {
        __onSurfaceChanged( __swiftObject, width, height );
    }

    /// public abstract void com.johnholdsworth.swiftbindings.SwiftHelloBinding$RenderListener.onSurfaceCreated()

    public native void __onSurfaceCreated( long __swiftObject );

    public void onSurfaceCreated() {
        __onSurfaceCreated( __swiftObject  );
    }

    public native void __finalize( long __swiftObject );

    public void finalize() {
        __finalize( __swiftObject );
    }

}
